/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermosRouteImport } from './routes/termos'
import { Route as RoadmapRouteImport } from './routes/roadmap'
import { Route as RankingRouteImport } from './routes/ranking'
import { Route as PrivacidadeRouteImport } from './routes/privacidade'
import { Route as GameRouteImport } from './routes/game'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as PerfilUserIdRouteImport } from './routes/perfil.$userId'
import { Route as ApiGenerateBgRouteImport } from './routes/api/generate-bg'
import { Route as AdminShopRouteImport } from './routes/admin.shop'
import { Route as AdminSetupRouteImport } from './routes/admin.setup'
import { Route as AdminPlayersRouteImport } from './routes/admin.players'
import { Route as AdminPaymentsRouteImport } from './routes/admin.payments'
import { Route as AdminLogsRouteImport } from './routes/admin.logs'
import { Route as AdminLiveopsRouteImport } from './routes/admin.liveops'
import { Route as AdminItemsRouteImport } from './routes/admin.items'
import { Route as AdminEventsRouteImport } from './routes/admin.events'
import { Route as AdminEconomyRouteImport } from './routes/admin.economy'
import { Route as AdminCodesRouteImport } from './routes/admin.codes'
import { Route as AdminBalancingRouteImport } from './routes/admin.balancing'
import { Route as ApiPublicHooksCloseSeasonRouteImport } from './routes/api/public/hooks/close-season'

const TermosRoute = TermosRouteImport.update({
  id: '/termos',
  path: '/termos',
  getParentRoute: () => rootRouteImport,
} as any)
const RoadmapRoute = RoadmapRouteImport.update({
  id: '/roadmap',
  path: '/roadmap',
  getParentRoute: () => rootRouteImport,
} as any)
const RankingRoute = RankingRouteImport.update({
  id: '/ranking',
  path: '/ranking',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadeRoute = PrivacidadeRouteImport.update({
  id: '/privacidade',
  path: '/privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const GameRoute = GameRouteImport.update({
  id: '/game',
  path: '/game',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const PerfilUserIdRoute = PerfilUserIdRouteImport.update({
  id: '/perfil/$userId',
  path: '/perfil/$userId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGenerateBgRoute = ApiGenerateBgRouteImport.update({
  id: '/api/generate-bg',
  path: '/api/generate-bg',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminShopRoute = AdminShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSetupRoute = AdminSetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPlayersRoute = AdminPlayersRouteImport.update({
  id: '/players',
  path: '/players',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPaymentsRoute = AdminPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLogsRoute = AdminLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLiveopsRoute = AdminLiveopsRouteImport.update({
  id: '/liveops',
  path: '/liveops',
  getParentRoute: () => AdminRoute,
} as any)
const AdminItemsRoute = AdminItemsRouteImport.update({
  id: '/items',
  path: '/items',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEventsRoute = AdminEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEconomyRoute = AdminEconomyRouteImport.update({
  id: '/economy',
  path: '/economy',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCodesRoute = AdminCodesRouteImport.update({
  id: '/codes',
  path: '/codes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBalancingRoute = AdminBalancingRouteImport.update({
  id: '/balancing',
  path: '/balancing',
  getParentRoute: () => AdminRoute,
} as any)
const ApiPublicHooksCloseSeasonRoute =
  ApiPublicHooksCloseSeasonRouteImport.update({
    id: '/api/public/hooks/close-season',
    path: '/api/public/hooks/close-season',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/game': typeof GameRoute
  '/privacidade': typeof PrivacidadeRoute
  '/ranking': typeof RankingRoute
  '/roadmap': typeof RoadmapRoute
  '/termos': typeof TermosRoute
  '/admin/balancing': typeof AdminBalancingRoute
  '/admin/codes': typeof AdminCodesRoute
  '/admin/economy': typeof AdminEconomyRoute
  '/admin/events': typeof AdminEventsRoute
  '/admin/items': typeof AdminItemsRoute
  '/admin/liveops': typeof AdminLiveopsRoute
  '/admin/logs': typeof AdminLogsRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/players': typeof AdminPlayersRoute
  '/admin/setup': typeof AdminSetupRoute
  '/admin/shop': typeof AdminShopRoute
  '/api/generate-bg': typeof ApiGenerateBgRoute
  '/perfil/$userId': typeof PerfilUserIdRoute
  '/admin/': typeof AdminIndexRoute
  '/api/public/hooks/close-season': typeof ApiPublicHooksCloseSeasonRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/game': typeof GameRoute
  '/privacidade': typeof PrivacidadeRoute
  '/ranking': typeof RankingRoute
  '/roadmap': typeof RoadmapRoute
  '/termos': typeof TermosRoute
  '/admin/balancing': typeof AdminBalancingRoute
  '/admin/codes': typeof AdminCodesRoute
  '/admin/economy': typeof AdminEconomyRoute
  '/admin/events': typeof AdminEventsRoute
  '/admin/items': typeof AdminItemsRoute
  '/admin/liveops': typeof AdminLiveopsRoute
  '/admin/logs': typeof AdminLogsRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/players': typeof AdminPlayersRoute
  '/admin/setup': typeof AdminSetupRoute
  '/admin/shop': typeof AdminShopRoute
  '/api/generate-bg': typeof ApiGenerateBgRoute
  '/perfil/$userId': typeof PerfilUserIdRoute
  '/admin': typeof AdminIndexRoute
  '/api/public/hooks/close-season': typeof ApiPublicHooksCloseSeasonRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/game': typeof GameRoute
  '/privacidade': typeof PrivacidadeRoute
  '/ranking': typeof RankingRoute
  '/roadmap': typeof RoadmapRoute
  '/termos': typeof TermosRoute
  '/admin/balancing': typeof AdminBalancingRoute
  '/admin/codes': typeof AdminCodesRoute
  '/admin/economy': typeof AdminEconomyRoute
  '/admin/events': typeof AdminEventsRoute
  '/admin/items': typeof AdminItemsRoute
  '/admin/liveops': typeof AdminLiveopsRoute
  '/admin/logs': typeof AdminLogsRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/players': typeof AdminPlayersRoute
  '/admin/setup': typeof AdminSetupRoute
  '/admin/shop': typeof AdminShopRoute
  '/api/generate-bg': typeof ApiGenerateBgRoute
  '/perfil/$userId': typeof PerfilUserIdRoute
  '/admin/': typeof AdminIndexRoute
  '/api/public/hooks/close-season': typeof ApiPublicHooksCloseSeasonRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/game'
    | '/privacidade'
    | '/ranking'
    | '/roadmap'
    | '/termos'
    | '/admin/balancing'
    | '/admin/codes'
    | '/admin/economy'
    | '/admin/events'
    | '/admin/items'
    | '/admin/liveops'
    | '/admin/logs'
    | '/admin/payments'
    | '/admin/players'
    | '/admin/setup'
    | '/admin/shop'
    | '/api/generate-bg'
    | '/perfil/$userId'
    | '/admin/'
    | '/api/public/hooks/close-season'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/game'
    | '/privacidade'
    | '/ranking'
    | '/roadmap'
    | '/termos'
    | '/admin/balancing'
    | '/admin/codes'
    | '/admin/economy'
    | '/admin/events'
    | '/admin/items'
    | '/admin/liveops'
    | '/admin/logs'
    | '/admin/payments'
    | '/admin/players'
    | '/admin/setup'
    | '/admin/shop'
    | '/api/generate-bg'
    | '/perfil/$userId'
    | '/admin'
    | '/api/public/hooks/close-season'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/game'
    | '/privacidade'
    | '/ranking'
    | '/roadmap'
    | '/termos'
    | '/admin/balancing'
    | '/admin/codes'
    | '/admin/economy'
    | '/admin/events'
    | '/admin/items'
    | '/admin/liveops'
    | '/admin/logs'
    | '/admin/payments'
    | '/admin/players'
    | '/admin/setup'
    | '/admin/shop'
    | '/api/generate-bg'
    | '/perfil/$userId'
    | '/admin/'
    | '/api/public/hooks/close-season'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  GameRoute: typeof GameRoute
  PrivacidadeRoute: typeof PrivacidadeRoute
  RankingRoute: typeof RankingRoute
  RoadmapRoute: typeof RoadmapRoute
  TermosRoute: typeof TermosRoute
  ApiGenerateBgRoute: typeof ApiGenerateBgRoute
  PerfilUserIdRoute: typeof PerfilUserIdRoute
  ApiPublicHooksCloseSeasonRoute: typeof ApiPublicHooksCloseSeasonRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/termos': {
      id: '/termos'
      path: '/termos'
      fullPath: '/termos'
      preLoaderRoute: typeof TermosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roadmap': {
      id: '/roadmap'
      path: '/roadmap'
      fullPath: '/roadmap'
      preLoaderRoute: typeof RoadmapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ranking': {
      id: '/ranking'
      path: '/ranking'
      fullPath: '/ranking'
      preLoaderRoute: typeof RankingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidade': {
      id: '/privacidade'
      path: '/privacidade'
      fullPath: '/privacidade'
      preLoaderRoute: typeof PrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/game': {
      id: '/game'
      path: '/game'
      fullPath: '/game'
      preLoaderRoute: typeof GameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/perfil/$userId': {
      id: '/perfil/$userId'
      path: '/perfil/$userId'
      fullPath: '/perfil/$userId'
      preLoaderRoute: typeof PerfilUserIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/generate-bg': {
      id: '/api/generate-bg'
      path: '/api/generate-bg'
      fullPath: '/api/generate-bg'
      preLoaderRoute: typeof ApiGenerateBgRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/shop': {
      id: '/admin/shop'
      path: '/shop'
      fullPath: '/admin/shop'
      preLoaderRoute: typeof AdminShopRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/setup': {
      id: '/admin/setup'
      path: '/setup'
      fullPath: '/admin/setup'
      preLoaderRoute: typeof AdminSetupRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/players': {
      id: '/admin/players'
      path: '/players'
      fullPath: '/admin/players'
      preLoaderRoute: typeof AdminPlayersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/payments': {
      id: '/admin/payments'
      path: '/payments'
      fullPath: '/admin/payments'
      preLoaderRoute: typeof AdminPaymentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/logs': {
      id: '/admin/logs'
      path: '/logs'
      fullPath: '/admin/logs'
      preLoaderRoute: typeof AdminLogsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/liveops': {
      id: '/admin/liveops'
      path: '/liveops'
      fullPath: '/admin/liveops'
      preLoaderRoute: typeof AdminLiveopsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/items': {
      id: '/admin/items'
      path: '/items'
      fullPath: '/admin/items'
      preLoaderRoute: typeof AdminItemsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/events': {
      id: '/admin/events'
      path: '/events'
      fullPath: '/admin/events'
      preLoaderRoute: typeof AdminEventsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/economy': {
      id: '/admin/economy'
      path: '/economy'
      fullPath: '/admin/economy'
      preLoaderRoute: typeof AdminEconomyRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/codes': {
      id: '/admin/codes'
      path: '/codes'
      fullPath: '/admin/codes'
      preLoaderRoute: typeof AdminCodesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/balancing': {
      id: '/admin/balancing'
      path: '/balancing'
      fullPath: '/admin/balancing'
      preLoaderRoute: typeof AdminBalancingRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/public/hooks/close-season': {
      id: '/api/public/hooks/close-season'
      path: '/api/public/hooks/close-season'
      fullPath: '/api/public/hooks/close-season'
      preLoaderRoute: typeof ApiPublicHooksCloseSeasonRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminBalancingRoute: typeof AdminBalancingRoute
  AdminCodesRoute: typeof AdminCodesRoute
  AdminEconomyRoute: typeof AdminEconomyRoute
  AdminEventsRoute: typeof AdminEventsRoute
  AdminItemsRoute: typeof AdminItemsRoute
  AdminLiveopsRoute: typeof AdminLiveopsRoute
  AdminLogsRoute: typeof AdminLogsRoute
  AdminPaymentsRoute: typeof AdminPaymentsRoute
  AdminPlayersRoute: typeof AdminPlayersRoute
  AdminSetupRoute: typeof AdminSetupRoute
  AdminShopRoute: typeof AdminShopRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminBalancingRoute: AdminBalancingRoute,
  AdminCodesRoute: AdminCodesRoute,
  AdminEconomyRoute: AdminEconomyRoute,
  AdminEventsRoute: AdminEventsRoute,
  AdminItemsRoute: AdminItemsRoute,
  AdminLiveopsRoute: AdminLiveopsRoute,
  AdminLogsRoute: AdminLogsRoute,
  AdminPaymentsRoute: AdminPaymentsRoute,
  AdminPlayersRoute: AdminPlayersRoute,
  AdminSetupRoute: AdminSetupRoute,
  AdminShopRoute: AdminShopRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  GameRoute: GameRoute,
  PrivacidadeRoute: PrivacidadeRoute,
  RankingRoute: RankingRoute,
  RoadmapRoute: RoadmapRoute,
  TermosRoute: TermosRoute,
  ApiGenerateBgRoute: ApiGenerateBgRoute,
  PerfilUserIdRoute: PerfilUserIdRoute,
  ApiPublicHooksCloseSeasonRoute: ApiPublicHooksCloseSeasonRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
